import type { WorkerWithUser, User, Booking, Payment } from './supabase';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-customer-1',
    name: 'Aditi Rao',
    email: 'customer@colabour.com',
    phone: '+91 98765 12340',
    role: 'customer',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-1',
    name: 'Rajesh Kumar',
    email: 'worker@colabour.com',
    phone: '+91 98765 43210',
    role: 'worker',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'usr-admin-1',
    name: 'CoLabour Admin',
    email: 'admin@colabour.com',
    phone: '+91 99999 00000',
    role: 'admin',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@colabour.com',
    phone: '+91 98123 45678',
    role: 'worker',
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-3',
    name: 'Amit Patel',
    email: 'amit.patel@colabour.com',
    phone: '+91 98234 56789',
    role: 'worker',
    created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-4',
    name: 'Sunita Verma',
    email: 'sunita.verma@colabour.com',
    phone: '+91 98345 67890',
    role: 'worker',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-5',
    name: 'Vikram Singh',
    email: 'vikram.singh@colabour.com',
    phone: '+91 98456 78901',
    role: 'worker',
    created_at: new Date(Date.now() - 70 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-6',
    name: 'Rahul Mehra',
    email: 'rahul.mehra@colabour.com',
    phone: '+91 98567 89012',
    role: 'worker',
    created_at: new Date(Date.now() - 65 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-7',
    name: 'Ananya Sen',
    email: 'ananya.sen@colabour.com',
    phone: '+91 98678 90123',
    role: 'worker',
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-8',
    name: 'Manoj Yadav',
    email: 'manoj.yadav@colabour.com',
    phone: '+91 98789 01234',
    role: 'worker',
    created_at: new Date(Date.now() - 85 * 86400000).toISOString(),
  },
  {
    id: 'usr-worker-9',
    name: 'Suresh Nair',
    email: 'suresh.nair@colabour.com',
    phone: '+91 98890 12345',
    role: 'worker',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
];

export const INITIAL_WORKERS: WorkerWithUser[] = [
  {
    id: 'wp-1',
    user_id: 'usr-worker-1',
    category: 'Electrician',
    bio: 'Certified master electrician with 8+ years experience in residential wiring, solar inverter setups, and emergency appliance repairs.',
    skills: ['Wiring', 'Inverter Setup', 'Appliance Repair', 'Circuit Breakers', 'Emergency Fixes'],
    upi_id: 'rajesh.kumar@okhdfcbank',
    hourly_rate: 450,
    rating: 4.9,
    total_ratings: 128,
    is_verified: true,
    location: 'Indiranagar, Bangalore',
    avatar_url: null,
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    users: {
      name: 'Rajesh Kumar',
      email: 'worker@colabour.com',
      phone: '+91 98765 43210',
    },
  },
  {
    id: 'wp-2',
    user_id: 'usr-worker-2',
    category: 'Cleaner',
    bio: 'Professional deep cleaning specialist for apartments, villas, and commercial offices. 100% eco-friendly and pet-safe products.',
    skills: ['Deep Cleaning', 'Sanitization', 'Kitchen & Bath', 'Sofa Shampooing', 'Eco-friendly'],
    upi_id: 'priya.sharma@paytm',
    hourly_rate: 350,
    rating: 4.8,
    total_ratings: 215,
    is_verified: true,
    location: 'Bandra West, Mumbai',
    avatar_url: null,
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
    users: {
      name: 'Priya Sharma',
      email: 'priya.sharma@colabour.com',
      phone: '+91 98123 45678',
    },
  },
  {
    id: 'wp-3',
    user_id: 'usr-worker-3',
    category: 'Plumber',
    bio: 'Licensed plumber specializing in high-pressure leak detection, concealed pipe fittings, geyser installations, and sanitary upgrades.',
    skills: ['Pipe Fitting', 'Leak Detection', 'Bathroom Fixtures', 'Geyser Repair', 'Drain Unclogging'],
    upi_id: 'amit.patel@icici',
    hourly_rate: 400,
    rating: 4.9,
    total_ratings: 94,
    is_verified: true,
    location: 'Hauz Khas, New Delhi',
    avatar_url: null,
    created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    users: {
      name: 'Amit Patel',
      email: 'amit.patel@colabour.com',
      phone: '+91 98234 56789',
    },
  },
  {
    id: 'wp-4',
    user_id: 'usr-worker-4',
    category: 'Caregiver',
    bio: 'Compassionate and certified elderly & post-operative caregiver. Trained in physiotherapy support, medication schedule, and vital signs monitoring.',
    skills: ['Elderly Care', 'First Aid', 'Medication Management', 'Patient Mobility', 'Vital Tracking'],
    upi_id: 'sunita.care@sbi',
    hourly_rate: 500,
    rating: 5.0,
    total_ratings: 82,
    is_verified: true,
    location: 'Kothrud, Pune',
    avatar_url: null,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    users: {
      name: 'Sunita Verma',
      email: 'sunita.verma@colabour.com',
      phone: '+91 98345 67890',
    },
  },
  {
    id: 'wp-5',
    user_id: 'usr-worker-5',
    category: 'Carpenter',
    bio: 'Master carpenter specializing in custom wooden furniture, modular kitchen fittings, precision lock repair, and antique polishing.',
    skills: ['Custom Furniture', 'Modular Kitchen', 'Door/Lock Repair', 'Wood Polishing', 'Cabinet Making'],
    upi_id: 'vikram.carpentry@axisbank',
    hourly_rate: 420,
    rating: 4.7,
    total_ratings: 140,
    is_verified: true,
    location: 'Gachibowli, Hyderabad',
    avatar_url: null,
    created_at: new Date(Date.now() - 70 * 86400000).toISOString(),
    users: {
      name: 'Vikram Singh',
      email: 'vikram.singh@colabour.com',
      phone: '+91 98456 78901',
    },
  },
  {
    id: 'wp-6',
    user_id: 'usr-worker-6',
    category: 'Painter',
    bio: 'Expert wall artist and interior painter. Precision roll work, moisture waterproofing, texture walls, and stencil painting.',
    skills: ['Interior Painting', 'Waterproofing', 'Texture Art', 'Wall Putty', 'Exterior Coating'],
    upi_id: 'rahul.paints@ybl',
    hourly_rate: 380,
    rating: 4.8,
    total_ratings: 110,
    is_verified: true,
    location: 'Adyar, Chennai',
    avatar_url: null,
    created_at: new Date(Date.now() - 65 * 86400000).toISOString(),
    users: {
      name: 'Rahul Mehra',
      email: 'rahul.mehra@colabour.com',
      phone: '+91 98567 89012',
    },
  },
  {
    id: 'wp-7',
    user_id: 'usr-worker-7',
    category: 'Technician',
    bio: 'HVAC & electronics technician. Inverter AC installation, copper gas refilling, PCB diagnostic, and smart appliance integration.',
    skills: ['AC Servicing', 'TV Mounting', 'Smart Home Setup', 'PCB Diagnostics', 'Gas Refill'],
    upi_id: 'ananya.tech@okaxis',
    hourly_rate: 550,
    rating: 4.9,
    total_ratings: 98,
    is_verified: true,
    location: 'Salt Lake, Kolkata',
    avatar_url: null,
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    users: {
      name: 'Ananya Sen',
      email: 'ananya.sen@colabour.com',
      phone: '+91 98678 90123',
    },
  },
  {
    id: 'wp-8',
    user_id: 'usr-worker-8',
    category: 'Driver',
    bio: 'Experienced professional driver with valid commercial license. Punctual, courteous, well-versed with highway and city navigation.',
    skills: ['City & Outstation', 'Luxury Sedans', 'Defensive Driving', 'Punctual', 'Manual & Auto'],
    upi_id: 'manoj.yadav@paytm',
    hourly_rate: 300,
    rating: 4.8,
    total_ratings: 320,
    is_verified: true,
    location: 'Whitefield, Bangalore',
    avatar_url: null,
    created_at: new Date(Date.now() - 85 * 86400000).toISOString(),
    users: {
      name: 'Manoj Yadav',
      email: 'manoj.yadav@colabour.com',
      phone: '+91 98789 01234',
    },
  },
  {
    id: 'wp-9',
    user_id: 'usr-worker-9',
    category: 'Gardener',
    bio: 'Horticulture lover providing organic lawn maintenance, terrace gardens, bonsai care, irrigation setup, and natural pest solutions.',
    skills: ['Landscape Design', 'Bonsai Care', 'Organic Lawn Care', 'Pest Treatment', 'Drip Irrigation'],
    upi_id: 'suresh.green@okhdfcbank',
    hourly_rate: 350,
    rating: 4.9,
    total_ratings: 76,
    is_verified: true,
    location: 'Kakkanad, Kochi',
    avatar_url: null,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    users: {
      name: 'Suresh Nair',
      email: 'suresh.nair@colabour.com',
      phone: '+91 98890 12345',
    },
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    customer_id: 'usr-customer-1',
    worker_id: 'wp-1',
    category: 'Electrician',
    scheduled_at: new Date(Date.now() + 2 * 86400000).toISOString(),
    address: 'Flat 402, Green Vista Apts, 12th Main Indiranagar, Bangalore',
    total_amount: 900,
    status: 'confirmed',
    notes: 'Please check the main switchboard and power socket in master bedroom.',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'bk-102',
    customer_id: 'usr-customer-1',
    worker_id: 'wp-2',
    category: 'Cleaner',
    scheduled_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    address: 'Flat 402, Green Vista Apts, 12th Main Indiranagar, Bangalore',
    total_amount: 1400,
    status: 'completed',
    notes: 'Deep cleaning of 2BHK including kitchen chimneys.',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-101',
    booking_id: 'bk-102',
    worker_id: 'wp-2',
    customer_id: 'usr-customer-1',
    amount: 1400,
    upi_uri: 'upi://pay?pa=priya.sharma@paytm&pn=Priya%20Sharma&am=1400&cu=INR&tn=CoLabour%20Booking%20bk-102',
    utr_number: 'UTR983410294812',
    verification_token: 'tok-verify-102',
    status: 'paid',
    paid_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];
