import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr';

const LANGUAGE_STORAGE_KEY = 'colabour-language';
const supportedLanguages: readonly Language[] = ['en', 'hi', 'mr'];

type TranslationSection = Record<string, string>;

interface TranslationStrings {
  language: TranslationSection;
  nav: TranslationSection;
  landing: TranslationSection;
  categories: TranslationSection;
  common: TranslationSection;
  auth: TranslationSection;
  directory: TranslationSection;
  profile: TranslationSection;
  booking: TranslationSection;
  payment: TranslationSection;
  customer: TranslationSection;
  workerDashboard: TranslationSection;
  admin: TranslationSection;
  alerts: TranslationSection;
  radar: TranslationSection;
  ai: TranslationSection;
  printer: TranslationSection;
}

const translations: Record<Language, TranslationStrings> = {
  en: {
    language: {
      select: 'Select language',
      english: 'English',
      hindi: 'Hindi',
      marathi: 'Marathi',
    },
    nav: {
      home: 'Home',
      workers: 'Workers',
      dashboard: 'Dashboard',
      worker: 'Worker',
      admin: 'Admin',
      myDashboard: 'My Dashboard',
      signIn: 'Sign In',
      getStarted: 'Get Started',
      signOut: 'Sign Out',
    },
    landing: {
      liveNetwork: 'Live Cooperative Network',
      heroTitleBefore: 'Find skilled',
      heroTitleHighlight: 'gig workers',
      heroTitleAfter: 'in seconds',
      heroDescription: 'CoLabour connects you with verified local professionals for instant bookings, transparent pricing, and seamless UPI payments. No middlemen, no hassle.',
      browseWorkers: 'Browse Workers',
      becomeWorker: 'Become a Worker',
      verifiedPros: 'Verified Pros',
      upiPayments: 'UPI Payments',
      instantBooking: 'Instant Booking',
      activeWorkers: 'Active Workers',
      jobsCompleted: 'Jobs Completed',
      averageRating: 'Avg Rating',
      onTimeRate: 'On-time Rate',
      categoriesTitle: 'Explore Categories',
      categoriesSubtitle: 'Browse by service category and find the right professional for your needs',
      categoryBook: 'Book a verified {{category}}',
      explore: 'Explore',
      howItWorksTitle: 'How It Works',
      howItWorksSubtitle: 'Three simple steps from booking to payment',
      findWorkerTitle: 'Find Your Worker',
      findWorkerDescription: 'Browse verified professionals by category, location, and rating. Compare rates and skills.',
      bookInstantlyTitle: 'Book Instantly',
      bookInstantlyDescription: 'Pick a time, set your location, and confirm. Your worker gets the request in real-time.',
      payViaUpiTitle: 'Pay via UPI',
      payViaUpiDescription: 'Scan the QR or tap to pay in your UPI app. Confirm with your UTR number. Done.',
      ctaTitle: 'Ready to get started?',
      ctaDescription: 'Join thousands of customers and workers on the CoLabour platform. Sign up free and start booking or earning today.',
      createAccount: 'Create Account',
      footer: 'CoLabour Marketplace. Next-Gen Gig Economy.',
      masterElectrician: 'Master Electrician',
      instantBookingConfirmed: 'Instant Booking Confirmed',
      deepCleaning: 'Deep Cleaning (2BHK)',
      today: 'Today, 2:00 PM',
      upiSettlement: 'UPI Instant Settlement',
      direct: '100% Direct',
      zeroPlatformFee: 'Zero Platform Fee',
    },
    categories: {
      Electrician: 'Electrician',
      Plumber: 'Plumber',
      Carpenter: 'Carpenter',
      Painter: 'Painter',
      Cleaner: 'Cleaner',
      Driver: 'Driver',
      Gardener: 'Gardener',
      Caregiver: 'Caregiver',
      Technician: 'Technician',
    },
    common: {
      unknown: 'Unknown',
      worker: 'Worker',
      professionalWorker: 'Professional Worker',
      verifiedCustomer: 'Verified Customer',
      customer: 'Customer',
      customerBooking: 'Customer Booking',
      professional: 'Professional',
      nearby: 'Nearby',
      all: 'All',
      accepted: 'Accepted',
      pending: 'Pending',
      completed: 'Completed',
      paid: 'Paid',
      cancelled: 'Cancelled',
      inProgress: 'In Progress',
      paymentSubmitted: 'Payment Submitted',
      reviews: 'reviews',
      hour: 'hour',
      hours: 'hours',
      mins: 'mins',
      kmAway: 'km away',
      minsReach: 'mins reach',
      zeroFee: 'Zero Fee',
    },
    auth: {
      passwordMinError: 'Password must be at least 6 characters in length',
      upiRequiredError: 'UPI ID is required for direct settlement routing',
      registrationFailed: 'Registration failed',
      accountExists: 'An account with this email address already exists. Please sign in.',
      signupTitle: 'Create your account',
      signupSubtitle: 'Join the verified gig workforce network with real-time settlement',
      accountType: 'Select Account Type',
      customer: 'Customer',
      customerDescription: 'Hire & book verified services',
      workerPro: 'Worker / Pro',
      workerDescription: 'Offer skills & get instant payouts',
      fullName: 'Full Name',
      phoneNumber: 'Phone Number',
      emailAddress: 'Email Address',
      password: 'Password',
      namePlaceholder: 'Aditi Rao',
      phonePlaceholder: '+91 98765 12340',
      emailSignupPlaceholder: 'aditi@example.com',
      passwordSignupPlaceholder: 'Min. 6 characters',
      verificationDetails: 'Professional Verification Details',
      serviceCategory: 'Service Category',
      directUpiId: 'Direct UPI ID',
      hourlyRate: 'Hourly Rate (₹)',
      operatingLocation: 'Operating City / Location',
      upiPlaceholder: 'rajesh.kumar@okhdfcbank',
      ratePlaceholder: '450',
      locationPlaceholder: 'Indiranagar, Bangalore',
      skillsSummary: 'Skills Summary (comma separated)',
      skillsPlaceholder: 'Wiring, Inverter Setup, Appliance Repair, Circuit Breakers',
      professionalBio: 'Professional Bio',
      bioPlaceholder: 'Master technician with 8+ years experience in domestic and commercial electrical repairs.',
      creatingAccount: 'Creating Account...',
      createAccount: 'Create Account',
      alreadyAccount: 'Already have an account?',
      signInAccount: 'Sign in to your account',
      welcomeBack: 'Welcome back',
      loginSubtitle: 'Sign in to access your dashboard and active jobs',
      emailLoginPlaceholder: 'name@example.com',
      passwordLoginPlaceholder: 'Your password',
      rememberDevice: 'Remember this device',
      encryptedSession: 'Encrypted Session',
      signingIn: 'Signing In...',
      signIn: 'Sign In',
      noAccount: "Don't have an account yet?",
      createAccountLink: 'Create an account',
      protectedSession: 'Protected by end-to-end encrypted session tokens & Supabase RLS',
      enterEmail: 'Please enter your email address',
      enterPassword: 'Please enter your password',
      invalidCredentials: 'Invalid credentials',
    },
    directory: {
      title: 'Find Your Worker',
      subtitle: 'Browse verified professionals across {{count}} categories with live GPS proximity',
      gpsActive: 'GPS Signal Active',
      calibrateGps: 'Calibrate Live GPS',
      searchPlaceholder: 'Search by name, skill, or location...',
      nearest: 'Nearest Live GPS',
      topRated: 'Top Rated',
      lowestRate: 'Lowest Rate',
      highestRate: 'Highest Rate',
      all: 'All',
      noWorkers: 'No workers found matching your criteria.',
      clearFilters: 'Clear filters',
      workerFallback: 'Worker',
      kmAway: '{{distance}} km away',
      minsReach: '~{{minutes}} mins reach',
    },
    profile: {
      cannotBookWorkers: 'Workers cannot book other workers. Please sign in as a customer.',
      workerNotFound: 'Worker not found.',
      browseWorkers: 'Browse Workers',
      backToWorkers: 'Back to Workers',
      unknownWorker: 'Unknown Worker',
      verified: 'Verified',
      reviews: '{{count}} reviews',
      perHour: '/hr',
      bookNow: 'Book Now',
      about: 'About',
      noBio: 'No bio provided.',
      skills: 'Skills & Specializations',
      highlights: 'Highlights',
      backgroundVerified: '100% Background Verified',
      directUpi: 'Direct UPI Payments',
      promptResponse: 'Prompt Response Rate',
      customWork: 'Need Custom Work?',
      customWorkDescription: 'You can specify exact requirements and provide special notes during the booking step.',
      requestService: 'Request Service',
      customerReviews: 'Customer Reviews ({{count}})',
      reviewOne: 'Extremely skilled, arrived right on time, and resolved the issue quickly. Highly recommended!',
      reviewTwo: 'Very courteous and professional. Clean work and fair hourly rate.',
    },
    booking: {
      currentGpsLocation: 'Current GPS Location (Lat: {{lat}}, Lng: {{lng}})',
      locationError: 'Could not get your location. Please enter address manually.',
      geoUnsupported: 'Geolocation is not supported on this device.',
      requiredFields: 'Please fill in all required fields',
      futureTime: 'Scheduled time must be in the future',
      createFailed: 'Failed to create booking',
      workerNotFound: 'Worker not found.',
      browseWorkers: 'Browse Workers',
      professionalWorker: 'Professional Worker',
      backToProfile: 'Back to Profile',
      title: 'Book Your Appointment',
      subtitle: 'Schedule a service with {{name}}',
      verifiedProfessional: 'Verified Professional',
      kmAway: '{{distance}} km away',
      minsReach: '~{{minutes}} mins reach',
      dateTime: 'Date & Time',
      date: 'Date',
      time: 'Time',
      duration: 'Duration (hours)',
      hours: 'hours',
      serviceLocation: 'Service Location & Live GPS',
      liveRadarReady: 'Live Radar Ready',
      address: 'Address / Flat / Landmark',
      addressPlaceholder: 'Enter your full address...',
      useGps: 'Use My Current GPS Location',
      liveProximity: 'Live Proximity: {{distance}} km',
      workerStationed: 'Worker is stationed near {{location}}',
      defaultLocation: 'Bangalore',
      problemNotes: 'Problem Description & Notes',
      notesPlaceholder: 'Describe the issue (e.g. Inverter tripping, bathroom pipe leak, fan capacitor replacement)...',
      summary: 'Booking Summary',
      worker: 'Worker',
      category: 'Category',
      durationValue: '{{hours}} hour(s)',
      rate: 'Rate',
      rateValue: '₹{{rate}}/hr',
      distance: 'Distance',
      distanceValue: '{{distance}} km (~{{minutes}} mins)',
      totalAmount: 'Total Amount (0% fee)',
      dispatching: 'Dispatching...',
      launchRadar: 'Launch GPS Radar & Match',
    },
    payment: {
      validUtr: 'Please enter a valid 12-digit UTR / Reference number',
      notFound: 'Booking or payment record not found.',
      goDashboard: 'Go to Dashboard',
      backDashboard: 'Back to Dashboard',
      closeSlip: 'Close Slip View',
      settlementCompleted: 'SETTLEMENT COMPLETED',
      professionalWorker: 'Professional Worker',
      verifiedCustomer: 'Verified Customer',
      successUtr: 'UPI-REF-SUCCESS',
      quickTest: 'Quick Test Slip / Toing',
      title: 'Payment Gateway',
      subtitle: 'Direct Worker Settlement powered by UPI',
      totalPayable: 'Total Payable Amount',
      workerVerifying: 'Worker Verifying UTR',
      workerAccepted: 'Worker Accepted & Ready',
      awaitingAcceptance: 'Awaiting Worker Acceptance',
      qrLocked: 'QR Code Locked',
      waitingFor: 'Waiting for {{name}} to accept this job request.',
      qrDescription: 'The UPI QR code and payment details will automatically unlock instantly once the worker clicks Accept on their dashboard.',
      livePolling: 'Live polling worker dispatch status...',
      jobConfirmed: 'Job Confirmed by {{name}}',
      liveUpi: 'Live UPI Channel',
      scanPay: 'Scan to Pay via UPI',
      scanWith: 'Scan with GPay, PhonePe, Paytm, or BHIM',
      workerUpi: 'WORKER UPI:',
      copied: 'Copied!',
      copy: 'Copy',
      launchApp: 'Or Launch Installed App Directly:',
      submitTitle: 'Submit UPI Reference (UTR)',
      submitDescription: 'After paying in your UPI app, enter the 12-digit transaction UTR number to submit for worker confirmation.',
      paymentSubmitted: 'Payment Submitted - Awaiting Worker Confirmation',
      submittedUtr: 'Submitted UTR: {{utr}}',
      alertDispatched: 'An instant alert has been dispatched to {{name}}. The slip will automatically print once verified.',
      polling: 'Polling worker confirmation status...',
      utrLabel: '12-Digit Bank UTR / Transaction Reference',
      utrPlaceholder: 'e.g. 483920194821',
      confirmFailed: 'Failed to confirm payment',
      workerFallback: 'Worker',
      submitting: 'Submitting to Worker...',
      submitButton: 'Submit for Worker Confirmation',
      protocol: 'CoLabour Direct-to-Worker UPI Protocol guarantees 0% commission deductions.',
    },
    customer: {
      dashboardTitle: 'My Customer Dashboard',
      welcome: 'Welcome back, {{name}}',
      bookWorker: 'Book a Worker',
      activeBookings: 'Active Bookings',
      completedPaid: 'Completed & Paid',
      totalSpent: 'Total Spent',
      pendingPayments: 'Pending Payments',
      pendingAlert: 'You have {{count}} pending payment action(s)',
      pendingDescription: 'Complete or track your UPI payment to settle your booking',
      openGateway: 'Open Payment Gateway',
      noActive: 'No active bookings',
      browseWorkers: 'Browse Workers',
      history: 'History & Official POS Slips',
      noCompleted: 'No completed bookings yet',
      workerFallback: 'Worker',
      statusAccepted: 'Accepted',
      statusPending: 'Pending',
      statusInProgress: 'In Progress',
      statusPaymentSubmitted: 'Payment Submitted',
      statusCompleted: 'Completed',
      statusPaid: 'Paid',
      statusCancelled: 'Cancelled',
      waitingAcceptance: 'Waiting for Acceptance',
      payWorker: 'Pay Worker via UPI',
      trackVerification: 'Track Verification',
      paymentSettled: 'Payment Settled',
      viewSlip: 'View CoLabour Slip',
      professionalWorker: 'Professional Worker',
      verifiedCustomer: 'Verified Customer',
      officialUtr: 'UPI-OFFICIAL-UTR',
    },
    workerDashboard: {
      paymentConfirmed: 'Payment confirmed as received!',
      confirmPaymentFailed: 'Failed to confirm payment',
      jobAccepted: '🎉 Job Accepted successfully! Customer notified to pay via UPI.',
      jobDeclined: 'Job Declined and removed from active queue.',
      jobCompleted: 'Job marked as Completed.',
      updateFailed: 'Failed to update booking status',
      settingsSaved: 'Settings saved successfully',
      settingsFailed: 'Failed to save settings',
      profileNotFound: 'Worker profile not found. Please complete your registration.',
      completeRegistration: 'Complete Registration',
      dashboard: "{{name}}'s Dashboard",
      workerId: 'Worker ID: {{id}}',
      upi: 'UPI: {{upi}}',
      verified: 'Verified',
      pending: 'Pending',
      settings: 'Settings',
      totalEarnings: 'Total Earnings',
      activeRequests: 'Active Requests',
      jobsSettled: 'Jobs Settled',
      rating: 'Rating',
      jobDispatches: 'Job Dispatches & Requests',
      noActiveRequests: 'No active job requests right now',
      paymentConfirmations: 'Payment Confirmations',
      noPayments: 'No customer payments waiting for your verification',
      settledJobs: 'Settled Jobs & CoLabour Slips',
      noCompletedJobs: 'No completed jobs yet',
      customerBooking: 'Customer Booking',
      utr: 'UTR: {{utr}}',
      viewSlip: 'View CoLabour Slip',
      workerSettings: 'Worker Settings',
      upiId: 'UPI ID',
      hourlyRate: 'Hourly Rate (₹)',
      save: 'Save',
      cancel: 'Cancel',
      customer: 'Customer',
      accepted: 'Accepted',
      note: 'Note: {{note}}',
      acceptJob: 'Accept Job',
      decline: 'Decline',
      acceptedPaying: 'Job Accepted • Customer paying via UPI',
      markComplete: 'Mark Complete',
      paymentAlert: 'Payment Received Alert',
      awaitingReceipt: 'Awaiting Receipt',
      yesReceived: 'Yes, Received (Confirm)',
      professional: 'Professional',
      verifiedCustomer: 'Verified Customer',
      officialUtr: 'OFFICIAL-PAID-UTR',
    },
    admin: {
      verificationFailed: 'Failed to update verification',
      disputeFailed: 'Failed to resolve dispute',
      title: 'Admin Command Center',
      subtitle: 'Platform-wide monitoring and management',
      totalRevenue: 'Total Revenue',
      totalWorkers: 'Total Workers',
      activeBookings: 'Active Bookings',
      openDisputes: 'Open Disputes',
      workerVerifications: 'Worker Verifications',
      pending: '{{count}} pending',
      noWorkers: 'No workers registered',
      unknown: 'Unknown',
      verified: 'Verified',
      disputeLogs: 'Dispute Logs',
      noDisputes: 'No disputes - all clear',
      paymentDispute: 'Payment Dispute',
      statusPending: 'Pending',
      utr: 'UTR: {{utr}}',
      amount: 'Amount: ₹{{amount}}',
      unresolved: 'Unresolved',
      resolve: 'Resolve & Mark Paid',
      telemetry: 'Platform Telemetry',
      totalBookings: 'Total Bookings',
      completed: 'Completed',
      verifiedWorkers: 'Verified Workers',
      totalPayments: 'Total Payments',
    },
    alerts: {
      acceptFailed: 'Failed to accept booking',
      declineFailed: 'Failed to decline booking',
      confirmFailed: 'Failed to confirm payment',
      rejectFailed: 'Failed to reject payment',
      highPriority: 'HIGH-PRIORITY JOB DISPATCH',
      newRequest: 'New Service Request!',
      requestDescription: 'A customer has requested your expertise on CoLabour.',
      customer: 'Customer:',
      category: 'Category / Skill:',
      totalValue: 'Total Value:',
      scheduledAt: 'Scheduled At:',
      location: 'Location:',
      verifiedCustomer: 'Verified Customer',
      customerNote: 'Customer Note:',
      decline: 'Decline',
      acceptJob: 'Accept Job',
      verificationRequired: 'PAYMENT VERIFICATION REQUIRED',
      paymentAlert: 'Payment Received Alert',
      paymentDescription: 'Customer submitted UPI confirmation for this job.',
      totalClaimed: 'Total Amount Claimed',
      bankUtr: '12-Digit Bank UTR:',
      notAvailable: 'N/A',
      timestamp: 'Timestamp:',
      checkPayment: 'Please check your UPI app / SMS alert for this transaction. Did you receive this payment?',
      notReceived: 'No, Not Received',
      yesReceived: 'Yes, Received',
    },
    radar: {
      detecting: 'Detecting your live GPS location...',
      scanning: 'Scanning nearby verified workers (within 5 km)...',
      matching: 'Matching closest professional...',
      found: 'Worker found! Live signal locked & waiting for acceptance',
      title: 'Live GPS Radar Matching',
      subtitle: 'CoLabour Proximity Dispatch',
      you: 'You',
      kmAway: '{{distance}} km away',
      minsReach: '~{{minutes}} mins reach time',
      statusSequence: 'STATUS SEQUENCE',
      nearby: 'Nearby',
      platformFee: '0% Platform Fee',
      lockProceed: 'Lock In & Proceed to Payment Gateway',
      acquiring: 'Acquiring Satellite Lock...',
    },
    ai: {
      quickWiring: '⚡ Estimate Wiring Cost',
      quickPlumber: '📍 Find Plumber Near Me',
      quickUpi: '💸 Zero-Fee UPI & UTR Guide',
      quickSlip: '🧾 How POS Slips Work',
      welcome: '👋 Namaste! I am CoLabour AI, your intelligent gig assistant. I can estimate repair costs, find the nearest verified professional, or explain our direct 0% commission UPI checkout.',
      launcher: 'Ask CoLabour AI',
      smart: 'Smart',
      title: 'CoLabour AI Assistant',
      subtitle: '0% Commission • Live Geolocation & Smart Pricing',
      mute: 'Mute AI Voice',
      enable: 'Enable AI Voice',
      inputPlaceholder: 'Ask about pricing, workers, or UPI payments...',
      electricalEstimate: '⚡ **Electrical Job Estimate:**\n• **Typical Cost:** ₹350 - ₹650 depending on points\n• **Est. Time:** 45 - 90 mins\n• **Zero Platform Fee:** ₹0 deducted from worker\n\nWould you like to book Rajesh Kumar (Top Rated Electrician, ₹450/hr)?',
      bookRajesh: 'Book Rajesh Kumar (Electrician)',
      plumbingMatch: '📍 **Plumbing Service Match:**\n• **Estimated Cost:** ₹300 - ₹500\n• **Typical Resolution:** 30 - 60 mins\n\nTop match: **{{name}}** (⭐ {{rating}}, ₹{{rate}}/hr). Verified for high-pressure leak repairs.',
      bookWorker: 'Book {{name}}',
      plumbingFallback: '📍 **Plumbing Service Match:**\nTop verified match is **Amit Patel** (⭐ 4.9, ₹400/hr). Specializes in concealed pipe repairs, tap fixes, and geysers.',
      bookAmit: 'Book Amit Patel (Plumber)',
      cleaning: '🧹 **Deep Cleaning & Sanitization:**\n• **1 BHK / Standard:** ₹700 - ₹1,200\n• **Kitchen & Bath Deep Clean:** ₹400 - ₹800\n• **Eco-friendly Products:** 100% pet safe\n\nTop match: **Priya Sharma** (⭐ 4.8, ₹350/hr).',
      bookPriya: 'Book Priya Sharma (Cleaner)',
      upiGuide: '💸 **How CoLabour Direct UPI Works:**\n1. **Direct Peer-to-Peer:** 100% of your money goes straight to the worker\'s bank account via UPI. CoLabour charges **0% commission**.\n2. **Locked State:** QR code unlocks as soon as the worker accepts your booking.\n3. **UTR Verification:** Enter your bank\'s 12-digit transaction ID (UTR) to instantly notify the worker.\n4. **Official POS Slip:** Receive a digitally signed POS thermal slip receipt.',
      browseWorkers: 'Browse Verified Workers',
      slipEngine: '🧾 **CoLabour 3D Thermal Slip Engine:**\nEvery completed and verified booking generates an official POS hardware receipt featuring:\n• Zero-fee breakdown\n• 12-digit Bank UTR record\n• Authenticated QR stamp\n• PDF download & direct thermal printer output.',
      openDashboard: 'Open Customer Dashboard',
      defaultResponse: '✨ I can help you find certified electricians, plumbers, carpenters, and cleaners with instant GPS proximity matching.\n\nTell me what you need fixed (e.g. "Fix ceiling fan", "Kitchen pipe leaking") or explore our directory of verified professionals.',
      exploreDirectory: 'Explore All Workers Directory',
    },
    printer: {
      terminal: 'COLABOUR-POS // 4.2K',
      online: 'ONLINE',
      ready: 'CoLabour Thermal POS Ready',
      readyDescription: 'Payment confirmed by worker. Push the button to dispense your tamper-proof digital work slip.',
      dispense: '⚡ TAP TO DISPENSE SLIP',
      printing: 'PRINTING THERMAL SLIP...',
      ejecting: 'Ejecting encrypted thermal receipt...',
      platform: 'On-Demand Skilled Services Platform',
      taxInvoice: 'TAX INVOICE / SERVICE RECEIPT',
      bookingId: 'BOOKING ID:',
      dateTime: 'DATE & TIME:',
      customer: 'CUSTOMER:',
      worker: 'WORKER:',
      category: 'CATEGORY:',
      workerUpi: 'WORKER UPI:',
      bankUtr: 'BANK UTR:',
      paymentStatus: 'PAYMENT STATUS:',
      confirmedPaid: 'CONFIRMED (PAID)',
      laborCharge: 'Labor Service Charge:',
      commission: 'Platform Commission:',
      zeroFee: '₹0.00 (Zero Fee)',
      totalPaid: 'TOTAL PAID:',
      verifiedSlip: 'VERIFIED SLIP',
      verifyAuthenticity: 'Scan to verify authenticity',
      secured: 'SECURED',
      thankYou: '*** THANK YOU FOR CHOOSING COLABOUR ***',
      printPdf: 'Print / Save PDF',
      backDashboard: 'Back to Dashboard',
    },
  },
  hi: {
    language: {
      select: 'भाषा चुनें',
      english: 'अंग्रेज़ी',
      hindi: 'हिन्दी',
      marathi: 'मराठी',
    },
    nav: {
      home: 'होम',
      workers: 'कामगार',
      dashboard: 'डैशबोर्ड',
      worker: 'कामगार',
      admin: 'एडमिन',
      myDashboard: 'मेरा डैशबोर्ड',
      signIn: 'साइन इन',
      getStarted: 'शुरू करें',
      signOut: 'साइन आउट',
    },
    landing: {
      liveNetwork: 'सक्रिय सहकारी नेटवर्क',
      heroTitleBefore: 'कुशल',
      heroTitleHighlight: 'गिग कामगार',
      heroTitleAfter: 'कुछ ही सेकंड में खोजें',
      heroDescription: 'CoLabour आपको तुरंत बुकिंग, पारदर्शी कीमतों और आसान UPI भुगतान के लिए सत्यापित स्थानीय पेशेवरों से जोड़ता है। कोई बिचौलिया नहीं, कोई परेशानी नहीं।',
      browseWorkers: 'कामगार खोजें',
      becomeWorker: 'कामगार बनें',
      verifiedPros: 'सत्यापित विशेषज्ञ',
      upiPayments: 'UPI भुगतान',
      instantBooking: 'तुरंत बुकिंग',
      activeWorkers: 'सक्रिय कामगार',
      jobsCompleted: 'पूरे किए गए काम',
      averageRating: 'औसत रेटिंग',
      onTimeRate: 'समय पर सेवा',
      categoriesTitle: 'श्रेणियां देखें',
      categoriesSubtitle: 'सेवा श्रेणी के अनुसार खोजें और अपनी जरूरत के लिए सही पेशेवर पाएं',
      categoryBook: 'सत्यापित {{category}} बुक करें',
      explore: 'देखें',
      howItWorksTitle: 'यह कैसे काम करता है',
      howItWorksSubtitle: 'बुकिंग से भुगतान तक तीन आसान चरण',
      findWorkerTitle: 'अपना कामगार खोजें',
      findWorkerDescription: 'श्रेणी, स्थान और रेटिंग के अनुसार सत्यापित पेशेवरों को देखें। दरों और कौशल की तुलना करें।',
      bookInstantlyTitle: 'तुरंत बुक करें',
      bookInstantlyDescription: 'समय चुनें, अपना स्थान डालें और पुष्टि करें। आपके कामगार को अनुरोध तुरंत मिल जाएगा।',
      payViaUpiTitle: 'UPI से भुगतान करें',
      payViaUpiDescription: 'QR स्कैन करें या अपने UPI ऐप में भुगतान करें। अपने UTR नंबर से पुष्टि करें। हो गया।',
      ctaTitle: 'शुरू करने के लिए तैयार हैं?',
      ctaDescription: 'CoLabour प्लेटफॉर्म पर हजारों ग्राहकों और कामगारों से जुड़ें। मुफ्त में साइन अप करें और आज ही बुकिंग या कमाई शुरू करें।',
      createAccount: 'खाता बनाएं',
      footer: 'CoLabour मार्केटप्लेस। नई पीढ़ी का गिग प्लेटफॉर्म।',
      masterElectrician: 'मास्टर इलेक्ट्रिशियन',
      instantBookingConfirmed: 'तुरंत बुकिंग की पुष्टि',
      deepCleaning: 'डीप क्लीनिंग (2BHK)',
      today: 'आज, दोपहर 2:00 बजे',
      upiSettlement: 'UPI तुरंत भुगतान',
      direct: '100% सीधे',
      zeroPlatformFee: 'शून्य प्लेटफॉर्म शुल्क',
    },
    categories: {
      Electrician: 'इलेक्ट्रिशियन',
      Plumber: 'प्लंबर',
      Carpenter: 'बढ़ई',
      Painter: 'पेंटर',
      Cleaner: 'सफाईकर्मी',
      Driver: 'ड्राइवर',
      Gardener: 'माली',
      Caregiver: 'देखभालकर्ता',
      Technician: 'तकनीशियन',
    },
    common: {
      unknown: 'अज्ञात',
      worker: 'कामगार',
      professionalWorker: 'पेशेवर कामगार',
      verifiedCustomer: 'सत्यापित ग्राहक',
      customer: 'ग्राहक',
      customerBooking: 'ग्राहक की बुकिंग',
      professional: 'पेशेवर',
      nearby: 'पास में',
      all: 'सभी',
      accepted: 'स्वीकृत',
      pending: 'लंबित',
      completed: 'पूर्ण',
      paid: 'भुगतान किया गया',
      cancelled: 'रद्द',
      inProgress: 'जारी',
      paymentSubmitted: 'भुगतान भेजा गया',
      reviews: 'समीक्षाएं',
      hour: 'घंटा',
      hours: 'घंटे',
      mins: 'मिनट',
      kmAway: 'किमी दूर',
      minsReach: 'मिनट में पहुंच',
      zeroFee: 'शून्य शुल्क',
    },
    auth: {
      passwordMinError: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      upiRequiredError: 'सीधे भुगतान के लिए UPI ID आवश्यक है',
      registrationFailed: 'पंजीकरण विफल रहा',
      accountExists: 'इस ईमेल से खाता पहले से मौजूद है। कृपया साइन इन करें।',
      signupTitle: 'अपना खाता बनाएं',
      signupSubtitle: 'रीयल-टाइम भुगतान वाले सत्यापित गिग नेटवर्क से जुड़ें',
      accountType: 'खाते का प्रकार चुनें',
      customer: 'ग्राहक',
      customerDescription: 'सत्यापित सेवाएं बुक करें',
      workerPro: 'कामगार / प्रो',
      workerDescription: 'अपना कौशल दें और तुरंत भुगतान पाएं',
      fullName: 'पूरा नाम',
      phoneNumber: 'फोन नंबर',
      emailAddress: 'ईमेल पता',
      password: 'पासवर्ड',
      namePlaceholder: 'अदिति राव',
      phonePlaceholder: '+91 98765 12340',
      emailSignupPlaceholder: 'aditi@example.com',
      passwordSignupPlaceholder: 'कम से कम 6 अक्षर',
      verificationDetails: 'पेशेवर सत्यापन विवरण',
      serviceCategory: 'सेवा श्रेणी',
      directUpiId: 'सीधी UPI ID',
      hourlyRate: 'प्रति घंटे की दर (₹)',
      operatingLocation: 'शहर / कार्य क्षेत्र',
      upiPlaceholder: 'rajesh.kumar@okhdfcbank',
      ratePlaceholder: '450',
      locationPlaceholder: 'इंदिरानगर, बेंगलुरु',
      skillsSummary: 'कौशल सारांश (अल्पविराम से अलग करें)',
      skillsPlaceholder: 'वायरिंग, इन्वर्टर सेटअप, उपकरण मरम्मत, सर्किट ब्रेकर',
      professionalBio: 'पेशेवर परिचय',
      bioPlaceholder: 'घरेलू और व्यावसायिक विद्युत मरम्मत में 8+ वर्षों का अनुभव।',
      creatingAccount: 'खाता बनाया जा रहा है...',
      createAccount: 'खाता बनाएं',
      alreadyAccount: 'क्या आपका खाता पहले से है?',
      signInAccount: 'अपने खाते में साइन इन करें',
      welcomeBack: 'वापसी पर स्वागत है',
      loginSubtitle: 'अपने डैशबोर्ड और सक्रिय काम देखने के लिए साइन इन करें',
      emailLoginPlaceholder: 'name@example.com',
      passwordLoginPlaceholder: 'अपना पासवर्ड',
      rememberDevice: 'इस डिवाइस को याद रखें',
      encryptedSession: 'एन्क्रिप्टेड सत्र',
      signingIn: 'साइन इन हो रहा है...',
      signIn: 'साइन इन',
      noAccount: 'अभी तक खाता नहीं है?',
      createAccountLink: 'खाता बनाएं',
      protectedSession: 'एंड-टू-एंड एन्क्रिप्टेड सत्र टोकन और Supabase RLS से सुरक्षित',
      enterEmail: 'कृपया अपना ईमेल पता दर्ज करें',
      enterPassword: 'कृपया अपना पासवर्ड दर्ज करें',
      invalidCredentials: 'गलत लॉगिन विवरण',
    },
    directory: {
      title: 'अपना कामगार खोजें',
      subtitle: 'लाइव GPS दूरी के साथ {{count}} श्रेणियों के सत्यापित पेशेवर देखें',
      gpsActive: 'GPS सिग्नल सक्रिय',
      calibrateGps: 'लाइव GPS कैलिब्रेट करें',
      searchPlaceholder: 'नाम, कौशल या स्थान से खोजें...',
      nearest: 'सबसे पास का लाइव GPS',
      topRated: 'सबसे अच्छी रेटिंग',
      lowestRate: 'सबसे कम दर',
      highestRate: 'सबसे अधिक दर',
      all: 'सभी',
      noWorkers: 'आपकी खोज से मेल खाते कामगार नहीं मिले।',
      clearFilters: 'फिल्टर हटाएं',
      workerFallback: 'कामगार',
      kmAway: '{{distance}} किमी दूर',
      minsReach: '~{{minutes}} मिनट में पहुंच',
    },
    profile: {
      cannotBookWorkers: 'कामगार दूसरे कामगारों को बुक नहीं कर सकते। कृपया ग्राहक के रूप में साइन इन करें।',
      workerNotFound: 'कामगार नहीं मिला।',
      browseWorkers: 'कामगार देखें',
      backToWorkers: 'कामगारों पर वापस जाएं',
      unknownWorker: 'अज्ञात कामगार',
      verified: 'सत्यापित',
      reviews: '{{count}} समीक्षाएं',
      perHour: '/घंटा',
      bookNow: 'अभी बुक करें',
      about: 'परिचय',
      noBio: 'कोई परिचय उपलब्ध नहीं है।',
      skills: 'कौशल और विशेषज्ञताएं',
      highlights: 'मुख्य विशेषताएं',
      backgroundVerified: '100% पृष्ठभूमि सत्यापित',
      directUpi: 'सीधा UPI भुगतान',
      promptResponse: 'त्वरित प्रतिक्रिया दर',
      customWork: 'विशेष काम चाहिए?',
      customWorkDescription: 'बुकिंग चरण में आप अपनी आवश्यकताएं और विशेष नोट्स दर्ज कर सकते हैं।',
      requestService: 'सेवा का अनुरोध करें',
      customerReviews: 'ग्राहक समीक्षाएं ({{count}})',
      reviewOne: 'बहुत कुशल, समय पर पहुंचे और समस्या जल्दी हल की। अत्यधिक अनुशंसित!',
      reviewTwo: 'बहुत विनम्र और पेशेवर। साफ काम और उचित प्रति घंटे की दर।',
    },
    booking: {
      currentGpsLocation: 'वर्तमान GPS स्थान (अक्षांश: {{lat}}, देशांतर: {{lng}})',
      locationError: 'आपका स्थान नहीं मिल सका। कृपया पता मैन्युअल रूप से दर्ज करें।',
      geoUnsupported: 'इस डिवाइस पर जियोलोकेशन उपलब्ध नहीं है।',
      requiredFields: 'कृपया सभी आवश्यक फ़ील्ड भरें',
      futureTime: 'निर्धारित समय भविष्य का होना चाहिए',
      createFailed: 'बुकिंग बनाना विफल रहा',
      workerNotFound: 'कामगार नहीं मिला।',
      browseWorkers: 'कामगार देखें',
      professionalWorker: 'पेशेवर कामगार',
      backToProfile: 'प्रोफ़ाइल पर वापस जाएं',
      title: 'अपॉइंटमेंट बुक करें',
      subtitle: '{{name}} के साथ सेवा निर्धारित करें',
      verifiedProfessional: 'सत्यापित पेशेवर',
      kmAway: '{{distance}} किमी दूर',
      minsReach: '~{{minutes}} मिनट में पहुंच',
      dateTime: 'दिनांक और समय',
      date: 'दिनांक',
      time: 'समय',
      duration: 'अवधि (घंटे)',
      hours: 'घंटे',
      serviceLocation: 'सेवा स्थान और लाइव GPS',
      liveRadarReady: 'लाइव रडार तैयार',
      address: 'पता / फ्लैट / लैंडमार्क',
      addressPlaceholder: 'अपना पूरा पता दर्ज करें...',
      useGps: 'मेरा वर्तमान GPS स्थान इस्तेमाल करें',
      liveProximity: 'लाइव दूरी: {{distance}} किमी',
      workerStationed: 'कामगार {{location}} के पास उपलब्ध है',
      defaultLocation: 'बेंगलुरु',
      problemNotes: 'समस्या का विवरण और नोट्स',
      notesPlaceholder: 'समस्या बताएं (जैसे इन्वर्टर ट्रिपिंग, बाथरूम पाइप लीकेज, पंखे का कैपेसिटर बदलना)...',
      summary: 'बुकिंग सारांश',
      worker: 'कामगार',
      category: 'श्रेणी',
      durationValue: '{{hours}} घंटे',
      rate: 'दर',
      rateValue: '₹{{rate}}/घंटा',
      distance: 'दूरी',
      distanceValue: '{{distance}} किमी (~{{minutes}} मिनट)',
      totalAmount: 'कुल राशि (0% शुल्क)',
      dispatching: 'भेजा जा रहा है...',
      launchRadar: 'GPS रडार और मिलान शुरू करें',
    },
    payment: {
      validUtr: 'कृपया मान्य 12 अंकों का UTR / संदर्भ नंबर दर्ज करें',
      notFound: 'बुकिंग या भुगतान रिकॉर्ड नहीं मिला।',
      goDashboard: 'डैशबोर्ड पर जाएं',
      backDashboard: 'डैशबोर्ड पर वापस जाएं',
      closeSlip: 'स्लिप दृश्य बंद करें',
      settlementCompleted: 'भुगतान पूरा हुआ',
      professionalWorker: 'पेशेवर कामगार',
      verifiedCustomer: 'सत्यापित ग्राहक',
      successUtr: 'UPI-REF-SUCCESS',
      quickTest: 'त्वरित टेस्ट स्लिप / Toing',
      title: 'भुगतान गेटवे',
      subtitle: 'UPI द्वारा सीधे कामगार को भुगतान',
      totalPayable: 'भुगतान योग्य कुल राशि',
      workerVerifying: 'कामगार UTR सत्यापित कर रहा है',
      workerAccepted: 'कामगार ने स्वीकार किया और तैयार है',
      awaitingAcceptance: 'कामगार की स्वीकृति का इंतजार',
      qrLocked: 'QR कोड लॉक है',
      waitingFor: '{{name}} के इस काम का अनुरोध स्वीकार करने का इंतजार है।',
      qrDescription: 'कामगार के डैशबोर्ड पर Accept दबाते ही UPI QR कोड और भुगतान विवरण अपने आप अनलॉक हो जाएंगे।',
      livePolling: 'कामगार की स्थिति लाइव जांची जा रही है...',
      jobConfirmed: '{{name}} ने काम की पुष्टि की',
      liveUpi: 'लाइव UPI चैनल',
      scanPay: 'UPI से भुगतान करने के लिए स्कैन करें',
      scanWith: 'GPay, PhonePe, Paytm या BHIM से स्कैन करें',
      workerUpi: 'कामगार UPI:',
      copied: 'कॉपी हो गया!',
      copy: 'कॉपी',
      launchApp: 'या इंस्टॉल किए गए ऐप से सीधे खोलें:',
      submitTitle: 'UPI संदर्भ (UTR) भेजें',
      submitDescription: 'UPI ऐप में भुगतान करने के बाद कामगार की पुष्टि के लिए 12 अंकों का UTR नंबर दर्ज करें।',
      paymentSubmitted: 'भुगतान भेजा गया - कामगार की पुष्टि का इंतजार',
      submittedUtr: 'भेजा गया UTR: {{utr}}',
      alertDispatched: '{{name}} को तुरंत सूचना भेज दी गई है। सत्यापन के बाद स्लिप अपने आप प्रिंट होगी।',
      polling: 'कामगार की पुष्टि की स्थिति जांची जा रही है...',
      utrLabel: '12 अंकों का बैंक UTR / लेनदेन संदर्भ',
      utrPlaceholder: 'उदा. 483920194821',
      confirmFailed: 'भुगतान की पुष्टि विफल रही',
      workerFallback: 'कामगार',
      submitting: 'कामगार को भेजा जा रहा है...',
      submitButton: 'कामगार की पुष्टि के लिए भेजें',
      protocol: 'CoLabour Direct-to-Worker UPI प्रोटोकॉल 0% कमीशन की गारंटी देता है।',
    },
    customer: {
      dashboardTitle: 'मेरा ग्राहक डैशबोर्ड',
      welcome: 'वापसी पर स्वागत है, {{name}}',
      bookWorker: 'कामगार बुक करें',
      activeBookings: 'सक्रिय बुकिंग',
      completedPaid: 'पूर्ण और भुगतान की गई',
      totalSpent: 'कुल खर्च',
      pendingPayments: 'लंबित भुगतान',
      pendingAlert: 'आपके {{count}} भुगतान कार्य लंबित हैं',
      pendingDescription: 'अपनी बुकिंग पूरी करने के लिए UPI भुगतान पूरा करें या उसकी स्थिति देखें',
      openGateway: 'भुगतान गेटवे खोलें',
      noActive: 'कोई सक्रिय बुकिंग नहीं',
      browseWorkers: 'कामगार देखें',
      history: 'इतिहास और आधिकारिक POS स्लिप',
      noCompleted: 'अभी कोई पूर्ण बुकिंग नहीं',
      workerFallback: 'कामगार',
      statusAccepted: 'स्वीकृत',
      statusPending: 'लंबित',
      statusInProgress: 'जारी',
      statusPaymentSubmitted: 'भुगतान भेजा गया',
      statusCompleted: 'पूर्ण',
      statusPaid: 'भुगतान किया गया',
      statusCancelled: 'रद्द',
      waitingAcceptance: 'स्वीकृति का इंतजार',
      payWorker: 'कामगार को UPI से भुगतान करें',
      trackVerification: 'सत्यापन ट्रैक करें',
      paymentSettled: 'भुगतान निपट गया',
      viewSlip: 'CoLabour स्लिप देखें',
      professionalWorker: 'पेशेवर कामगार',
      verifiedCustomer: 'सत्यापित ग्राहक',
      officialUtr: 'UPI-OFFICIAL-UTR',
    },
    workerDashboard: {
      paymentConfirmed: 'भुगतान प्राप्त होने की पुष्टि हुई!',
      confirmPaymentFailed: 'भुगतान की पुष्टि विफल रही',
      jobAccepted: '🎉 काम सफलतापूर्वक स्वीकार किया! ग्राहक को UPI से भुगतान करने की सूचना दी गई।',
      jobDeclined: 'काम अस्वीकार कर सक्रिय सूची से हटा दिया गया।',
      jobCompleted: 'काम पूर्ण के रूप में चिह्नित किया गया।',
      updateFailed: 'बुकिंग स्थिति अपडेट करना विफल रहा',
      settingsSaved: 'सेटिंग्स सफलतापूर्वक सेव की गईं',
      settingsFailed: 'सेटिंग्स सेव करना विफल रहा',
      profileNotFound: 'कामगार प्रोफ़ाइल नहीं मिली। कृपया अपना पंजीकरण पूरा करें।',
      completeRegistration: 'पंजीकरण पूरा करें',
      dashboard: '{{name}} का डैशबोर्ड',
      workerId: 'कामगार ID: {{id}}',
      upi: 'UPI: {{upi}}',
      verified: 'सत्यापित',
      pending: 'लंबित',
      settings: 'सेटिंग्स',
      totalEarnings: 'कुल कमाई',
      activeRequests: 'सक्रिय अनुरोध',
      jobsSettled: 'निपटाए गए काम',
      rating: 'रेटिंग',
      jobDispatches: 'काम वितरण और अनुरोध',
      noActiveRequests: 'अभी कोई सक्रिय काम अनुरोध नहीं है',
      paymentConfirmations: 'भुगतान पुष्टिकरण',
      noPayments: 'आपके सत्यापन के लिए कोई ग्राहक भुगतान लंबित नहीं है',
      settledJobs: 'निपटाए गए काम और CoLabour स्लिप',
      noCompletedJobs: 'अभी कोई पूर्ण काम नहीं',
      customerBooking: 'ग्राहक की बुकिंग',
      utr: 'UTR: {{utr}}',
      viewSlip: 'CoLabour स्लिप देखें',
      workerSettings: 'कामगार सेटिंग्स',
      upiId: 'UPI ID',
      hourlyRate: 'प्रति घंटे की दर (₹)',
      save: 'सेव करें',
      cancel: 'रद्द करें',
      customer: 'ग्राहक',
      accepted: 'स्वीकृत',
      note: 'नोट: {{note}}',
      acceptJob: 'काम स्वीकार करें',
      decline: 'अस्वीकार करें',
      acceptedPaying: 'काम स्वीकार • ग्राहक UPI से भुगतान कर रहा है',
      markComplete: 'पूर्ण चिह्नित करें',
      paymentAlert: 'भुगतान प्राप्ति सूचना',
      awaitingReceipt: 'रसीद की प्रतीक्षा',
      yesReceived: 'हां, प्राप्त हुआ (पुष्टि करें)',
      professional: 'पेशेवर',
      verifiedCustomer: 'सत्यापित ग्राहक',
      officialUtr: 'OFFICIAL-PAID-UTR',
    },
    admin: {
      verificationFailed: 'सत्यापन अपडेट करना विफल रहा',
      disputeFailed: 'विवाद हल करना विफल रहा',
      title: 'एडमिन कमांड सेंटर',
      subtitle: 'पूरे प्लेटफॉर्म की निगरानी और प्रबंधन',
      totalRevenue: 'कुल आय',
      totalWorkers: 'कुल कामगार',
      activeBookings: 'सक्रिय बुकिंग',
      openDisputes: 'खुले विवाद',
      workerVerifications: 'कामगार सत्यापन',
      pending: '{{count}} लंबित',
      noWorkers: 'कोई कामगार पंजीकृत नहीं',
      unknown: 'अज्ञात',
      verified: 'सत्यापित',
      disputeLogs: 'विवाद लॉग',
      noDisputes: 'कोई विवाद नहीं - सब ठीक है',
      paymentDispute: 'भुगतान विवाद',
      statusPending: 'लंबित',
      utr: 'UTR: {{utr}}',
      amount: 'राशि: ₹{{amount}}',
      unresolved: 'अनसुलझा',
      resolve: 'हल करें और भुगतान चिह्नित करें',
      telemetry: 'प्लेटफॉर्म टेलीमेट्री',
      totalBookings: 'कुल बुकिंग',
      completed: 'पूर्ण',
      verifiedWorkers: 'सत्यापित कामगार',
      totalPayments: 'कुल भुगतान',
    },
    alerts: {
      acceptFailed: 'बुकिंग स्वीकार करना विफल रहा',
      declineFailed: 'बुकिंग अस्वीकार करना विफल रहा',
      confirmFailed: 'भुगतान की पुष्टि विफल रही',
      rejectFailed: 'भुगतान अस्वीकार करना विफल रहा',
      highPriority: 'उच्च प्राथमिकता काम वितरण',
      newRequest: 'नई सेवा का अनुरोध!',
      requestDescription: 'एक ग्राहक ने CoLabour पर आपकी विशेषज्ञता का अनुरोध किया है।',
      customer: 'ग्राहक:',
      category: 'श्रेणी / कौशल:',
      totalValue: 'कुल मूल्य:',
      scheduledAt: 'निर्धारित समय:',
      location: 'स्थान:',
      verifiedCustomer: 'सत्यापित ग्राहक',
      customerNote: 'ग्राहक का नोट:',
      decline: 'अस्वीकार करें',
      acceptJob: 'काम स्वीकार करें',
      verificationRequired: 'भुगतान सत्यापन आवश्यक',
      paymentAlert: 'भुगतान प्राप्ति सूचना',
      paymentDescription: 'ग्राहक ने इस काम के लिए UPI भुगतान की पुष्टि भेजी है।',
      totalClaimed: 'दावा की गई कुल राशि',
      bankUtr: '12 अंकों का बैंक UTR:',
      notAvailable: 'उपलब्ध नहीं',
      timestamp: 'समय:',
      checkPayment: 'इस लेनदेन के लिए अपना UPI ऐप / SMS अलर्ट देखें। क्या आपको यह भुगतान मिला?',
      notReceived: 'नहीं, प्राप्त नहीं हुआ',
      yesReceived: 'हां, प्राप्त हुआ',
    },
    radar: {
      detecting: 'आपका लाइव GPS स्थान खोजा जा रहा है...',
      scanning: '5 किमी के भीतर सत्यापित कामगार खोजे जा रहे हैं...',
      matching: 'सबसे नजदीकी पेशेवर से मिलान किया जा रहा है...',
      found: 'कामगार मिल गया! लाइव सिग्नल लॉक है और स्वीकृति का इंतजार है',
      title: 'लाइव GPS रडार मिलान',
      subtitle: 'CoLabour नजदीकी वितरण',
      you: 'आप',
      kmAway: '{{distance}} किमी',
      minsReach: '~{{minutes}} मिनट में पहुंच',
      statusSequence: 'स्थिति क्रम',
      nearby: 'पास में',
      platformFee: '0% प्लेटफॉर्म शुल्क',
      lockProceed: 'लॉक करें और भुगतान गेटवे पर जाएं',
      acquiring: 'सैटेलाइट लॉक प्राप्त किया जा रहा है...',
    },
    ai: {
      quickWiring: '⚡ वायरिंग की लागत जानें',
      quickPlumber: '📍 मेरे पास प्लंबर खोजें',
      quickUpi: '💸 शून्य शुल्क UPI और UTR गाइड',
      quickSlip: '🧾 POS स्लिप कैसे काम करती है',
      welcome: '👋 नमस्ते! मैं CoLabour AI हूं, आपका स्मार्ट गिग सहायक। मैं मरम्मत की लागत बता सकता हूं, सबसे नजदीकी सत्यापित पेशेवर खोज सकता हूं या सीधे 0% कमीशन UPI भुगतान को समझा सकता हूं।',
      launcher: 'CoLabour AI से पूछें',
      smart: 'स्मार्ट',
      title: 'CoLabour AI सहायक',
      subtitle: '0% कमीशन • लाइव जियोलोकेशन और स्मार्ट कीमतें',
      mute: 'AI आवाज बंद करें',
      enable: 'AI आवाज चालू करें',
      inputPlaceholder: 'कीमत, कामगार या UPI भुगतान के बारे में पूछें...',
      electricalEstimate: '⚡ **विद्युत काम का अनुमान:**\n• **सामान्य लागत:** पॉइंट के अनुसार ₹350 - ₹650\n• **अनुमानित समय:** 45 - 90 मिनट\n• **शून्य प्लेटफॉर्म शुल्क:** कामगार से ₹0 कटौती\n\nक्या आप राजेश कुमार (टॉप रेटेड इलेक्ट्रिशियन, ₹450/घंटा) को बुक करना चाहेंगे?',
      bookRajesh: 'राजेश कुमार बुक करें (इलेक्ट्रिशियन)',
      plumbingMatch: '📍 **प्लंबिंग सेवा मिलान:**\n• **अनुमानित लागत:** ₹300 - ₹500\n• **सामान्य समाधान समय:** 30 - 60 मिनट\n\nसबसे अच्छा मिलान: **{{name}}** (⭐ {{rating}}, ₹{{rate}}/घंटा)। हाई-प्रेशर लीकेज मरम्मत के लिए सत्यापित।',
      bookWorker: '{{name}} बुक करें',
      plumbingFallback: '📍 **प्लंबिंग सेवा मिलान:**\nसबसे अच्छा सत्यापित मिलान **अमित पटेल** (⭐ 4.9, ₹400/घंटा) है। छिपे पाइप की मरम्मत, नल और गीजर में विशेषज्ञ।',
      bookAmit: 'अमित पटेल बुक करें (प्लंबर)',
      cleaning: '🧹 **डीप क्लीनिंग और सैनिटाइजेशन:**\n• **1 BHK / सामान्य:** ₹700 - ₹1,200\n• **किचन और बाथ डीप क्लीन:** ₹400 - ₹800\n• **पर्यावरण-अनुकूल उत्पाद:** पालतू जानवरों के लिए 100% सुरक्षित\n\nसबसे अच्छा मिलान: **प्रिया शर्मा** (⭐ 4.8, ₹350/घंटा)।',
      bookPriya: 'प्रिया शर्मा बुक करें (क्लीनर)',
      upiGuide: '💸 **CoLabour Direct UPI कैसे काम करता है:**\n1. **सीधा व्यक्ति-से-व्यक्ति:** आपका 100% पैसा UPI से सीधे कामगार के बैंक खाते में जाता है। CoLabour **0% कमीशन** लेता है।\n2. **लॉक स्थिति:** कामगार के बुकिंग स्वीकार करते ही QR कोड खुल जाता है।\n3. **UTR सत्यापन:** कामगार को तुरंत सूचना देने के लिए अपने बैंक का 12 अंकों का लेनदेन ID (UTR) दर्ज करें।\n4. **आधिकारिक POS स्लिप:** डिजिटल रूप से हस्ताक्षरित POS थर्मल स्लिप पाएं।',
      browseWorkers: 'सत्यापित कामगार देखें',
      slipEngine: '🧾 **CoLabour 3D थर्मल स्लिप इंजन:**\nहर पूर्ण और सत्यापित बुकिंग पर आधिकारिक POS हार्डवेयर रसीद बनती है, जिसमें शामिल है:\n• शून्य शुल्क विवरण\n• 12 अंकों का बैंक UTR रिकॉर्ड\n• प्रमाणित QR स्टाम्प\n• PDF डाउनलोड और सीधे थर्मल प्रिंटर से आउटपुट।',
      openDashboard: 'ग्राहक डैशबोर्ड खोलें',
      defaultResponse: '✨ मैं तत्काल GPS दूरी मिलान के साथ प्रमाणित इलेक्ट्रिशियन, प्लंबर, बढ़ई और क्लीनर खोजने में मदद कर सकता हूं।\n\nबताएं कि क्या ठीक करवाना है (जैसे "सीलिंग फैन ठीक करें", "किचन पाइप लीक है") या सत्यापित पेशेवरों की डायरेक्टरी देखें।',
      exploreDirectory: 'सभी कामगारों की डायरेक्टरी देखें',
    },
    printer: {
      terminal: 'COLABOUR-POS // 4.2K',
      online: 'ऑनलाइन',
      ready: 'CoLabour थर्मल POS तैयार',
      readyDescription: 'कामगार ने भुगतान की पुष्टि कर दी है। छेड़छाड़-रोधी डिजिटल काम की स्लिप निकालने के लिए बटन दबाएं।',
      dispense: '⚡ स्लिप निकालने के लिए टैप करें',
      printing: 'थर्मल स्लिप प्रिंट हो रही है...',
      ejecting: 'एन्क्रिप्टेड थर्मल रसीद निकाली जा रही है...',
      platform: 'ऑन-डिमांड कुशल सेवा प्लेटफॉर्म',
      taxInvoice: 'टैक्स इनवॉइस / सेवा रसीद',
      bookingId: 'बुकिंग ID:',
      dateTime: 'दिनांक और समय:',
      customer: 'ग्राहक:',
      worker: 'कामगार:',
      category: 'श्रेणी:',
      workerUpi: 'कामगार UPI:',
      bankUtr: 'बैंक UTR:',
      paymentStatus: 'भुगतान स्थिति:',
      confirmedPaid: 'पुष्टि हुई (भुगतान किया गया)',
      laborCharge: 'सेवा शुल्क:',
      commission: 'प्लेटफॉर्म कमीशन:',
      zeroFee: '₹0.00 (शून्य शुल्क)',
      totalPaid: 'कुल भुगतान:',
      verifiedSlip: 'सत्यापित स्लिप',
      verifyAuthenticity: 'प्रामाणिकता जांचने के लिए स्कैन करें',
      secured: 'सुरक्षित',
      thankYou: '*** CoLabour चुनने के लिए धन्यवाद ***',
      printPdf: 'प्रिंट / PDF सेव करें',
      backDashboard: 'डैशबोर्ड पर वापस जाएं',
    },
  },
  mr: {
    language: {
      select: 'भाषा निवडा',
      english: 'इंग्रजी',
      hindi: 'हिंदी',
      marathi: 'मराठी',
    },
    nav: {
      home: 'मुख्यपृष्ठ',
      workers: 'कामगार',
      dashboard: 'डॅशबोर्ड',
      worker: 'कामगार',
      admin: 'अॅडमिन',
      myDashboard: 'माझे डॅशबोर्ड',
      signIn: 'साइन इन',
      getStarted: 'सुरुवात करा',
      signOut: 'साइन आउट',
    },
    landing: {
      liveNetwork: 'सक्रिय सहकारी नेटवर्क',
      heroTitleBefore: 'कुशल',
      heroTitleHighlight: 'गिग कामगार',
      heroTitleAfter: 'काही सेकंदांत शोधा',
      heroDescription: 'CoLabour तुम्हाला त्वरित बुकिंग, पारदर्शक दर आणि सोप्या UPI पेमेंटसाठी सत्यापित स्थानिक व्यावसायिकांशी जोडते. मध्यस्थ नाहीत, त्रास नाही.',
      browseWorkers: 'कामगार शोधा',
      becomeWorker: 'कामगार बना',
      verifiedPros: 'सत्यापित तज्ज्ञ',
      upiPayments: 'UPI पेमेंट',
      instantBooking: 'त्वरित बुकिंग',
      activeWorkers: 'सक्रिय कामगार',
      jobsCompleted: 'पूर्ण झालेली कामे',
      averageRating: 'सरासरी रेटिंग',
      onTimeRate: 'वेळेवर सेवा',
      categoriesTitle: 'श्रेणी पाहा',
      categoriesSubtitle: 'सेवा श्रेणीनुसार शोधा आणि तुमच्या गरजेसाठी योग्य व्यावसायिक शोधा',
      categoryBook: 'सत्यापित {{category}} बुक करा',
      explore: 'पाहा',
      howItWorksTitle: 'हे कसे कार्य करते',
      howItWorksSubtitle: 'बुकिंगपासून पेमेंटपर्यंत तीन सोप्या पायऱ्या',
      findWorkerTitle: 'तुमचा कामगार शोधा',
      findWorkerDescription: 'श्रेणी, ठिकाण आणि रेटिंगनुसार सत्यापित व्यावसायिक पाहा. दर आणि कौशल्यांची तुलना करा.',
      bookInstantlyTitle: 'त्वरित बुक करा',
      bookInstantlyDescription: 'वेळ निवडा, तुमचे ठिकाण द्या आणि पुष्टी करा. तुमच्या कामगाराला विनंती लगेच मिळेल.',
      payViaUpiTitle: 'UPI द्वारे पेमेंट करा',
      payViaUpiDescription: 'QR स्कॅन करा किंवा तुमच्या UPI अॅपमधून पेमेंट करा. UTR क्रमांकाने पुष्टी करा. झाले.',
      ctaTitle: 'सुरुवात करण्यासाठी तयार आहात?',
      ctaDescription: 'CoLabour प्लॅटफॉर्मवरील हजारो ग्राहक आणि कामगारांशी जोडा. मोफत साइन अप करा आणि आजच बुकिंग किंवा कमाई सुरू करा.',
      createAccount: 'खाते तयार करा',
      footer: 'CoLabour मार्केटप्लेस. नव्या पिढीचे गिग प्लॅटफॉर्म.',
      masterElectrician: 'मास्टर इलेक्ट्रिशियन',
      instantBookingConfirmed: 'त्वरित बुकिंग निश्चित',
      deepCleaning: 'डीप क्लीनिंग (2BHK)',
      today: 'आज, दुपारी 2:00 वाजता',
      upiSettlement: 'UPI त्वरित सेटलमेंट',
      direct: '100% थेट',
      zeroPlatformFee: 'शून्य प्लॅटफॉर्म शुल्क',
    },
    categories: {
      Electrician: 'इलेक्ट्रिशियन',
      Plumber: 'प्लंबर',
      Carpenter: 'सुतार',
      Painter: 'पेंटर',
      Cleaner: 'सफाई कामगार',
      Driver: 'ड्रायव्हर',
      Gardener: 'माळी',
      Caregiver: 'काळजीवाहक',
      Technician: 'तंत्रज्ञ',
    },
    common: {
      unknown: 'अज्ञात',
      worker: 'कामगार',
      professionalWorker: 'व्यावसायिक कामगार',
      verifiedCustomer: 'सत्यापित ग्राहक',
      customer: 'ग्राहक',
      customerBooking: 'ग्राहकाचे बुकिंग',
      professional: 'व्यावसायिक',
      nearby: 'जवळपास',
      all: 'सर्व',
      accepted: 'स्वीकारले',
      pending: 'प्रलंबित',
      completed: 'पूर्ण',
      paid: 'पैसे दिले',
      cancelled: 'रद्द',
      inProgress: 'प्रगतीपथावर',
      paymentSubmitted: 'पेमेंट पाठवले',
      reviews: 'परीक्षणे',
      hour: 'तास',
      hours: 'तास',
      mins: 'मिनिटे',
      kmAway: 'किमी दूर',
      minsReach: 'मिनिटांत पोहोच',
      zeroFee: 'शून्य शुल्क',
    },
    auth: {
      passwordMinError: 'पासवर्ड किमान 6 अक्षरांचा असावा',
      upiRequiredError: 'थेट पेमेंटसाठी UPI ID आवश्यक आहे',
      registrationFailed: 'नोंदणी अयशस्वी झाली',
      accountExists: 'या ईमेलचा खाते आधीपासून आहे. कृपया साइन इन करा.',
      signupTitle: 'तुमचे खाते तयार करा',
      signupSubtitle: 'रिअल-टाइम पेमेंट असलेल्या सत्यापित गिग नेटवर्कमध्ये सामील व्हा',
      accountType: 'खात्याचा प्रकार निवडा',
      customer: 'ग्राहक',
      customerDescription: 'सत्यापित सेवा बुक करा',
      workerPro: 'कामगार / प्रो',
      workerDescription: 'तुमचे कौशल्य द्या आणि त्वरित पेमेंट मिळवा',
      fullName: 'पूर्ण नाव',
      phoneNumber: 'फोन नंबर',
      emailAddress: 'ईमेल पत्ता',
      password: 'पासवर्ड',
      namePlaceholder: 'अदिती राव',
      phonePlaceholder: '+91 98765 12340',
      emailSignupPlaceholder: 'aditi@example.com',
      passwordSignupPlaceholder: 'किमान 6 अक्षरे',
      verificationDetails: 'व्यावसायिक सत्यापन तपशील',
      serviceCategory: 'सेवा श्रेणी',
      directUpiId: 'थेट UPI ID',
      hourlyRate: 'तासाचा दर (₹)',
      operatingLocation: 'शहर / कार्यक्षेत्र',
      upiPlaceholder: 'rajesh.kumar@okhdfcbank',
      ratePlaceholder: '450',
      locationPlaceholder: 'इंदिरानगर, बेंगळुरू',
      skillsSummary: 'कौशल्य सारांश (स्वल्पविरामाने वेगळे करा)',
      skillsPlaceholder: 'वायरिंग, इन्व्हर्टर सेटअप, उपकरण दुरुस्ती, सर्किट ब्रेकर',
      professionalBio: 'व्यावसायिक परिचय',
      bioPlaceholder: 'घरगुती आणि व्यावसायिक विद्युत दुरुस्तीचा 8+ वर्षांचा अनुभव.',
      creatingAccount: 'खाते तयार होत आहे...',
      createAccount: 'खाते तयार करा',
      alreadyAccount: 'आधीच खाते आहे?',
      signInAccount: 'तुमच्या खात्यात साइन इन करा',
      welcomeBack: 'पुन्हा स्वागत आहे',
      loginSubtitle: 'डॅशबोर्ड आणि सक्रिय कामे पाहण्यासाठी साइन इन करा',
      emailLoginPlaceholder: 'name@example.com',
      passwordLoginPlaceholder: 'तुमचा पासवर्ड',
      rememberDevice: 'हे डिव्हाइस लक्षात ठेवा',
      encryptedSession: 'एन्क्रिप्टेड सत्र',
      signingIn: 'साइन इन होत आहे...',
      signIn: 'साइन इन',
      noAccount: 'अजून खाते नाही?',
      createAccountLink: 'खाते तयार करा',
      protectedSession: 'एंड-टू-एंड एन्क्रिप्टेड सत्र टोकन आणि Supabase RLS द्वारे सुरक्षित',
      enterEmail: 'कृपया तुमचा ईमेल पत्ता टाका',
      enterPassword: 'कृपया तुमचा पासवर्ड टाका',
      invalidCredentials: 'चुकीची लॉगिन माहिती',
    },
    directory: {
      title: 'तुमचा कामगार शोधा',
      subtitle: 'लाइव्ह GPS अंतरासह {{count}} श्रेणीतील सत्यापित व्यावसायिक पाहा',
      gpsActive: 'GPS सिग्नल सक्रिय',
      calibrateGps: 'लाइव्ह GPS कॅलिब्रेट करा',
      searchPlaceholder: 'नाव, कौशल्य किंवा ठिकाणाने शोधा...',
      nearest: 'सर्वात जवळचा लाइव्ह GPS',
      topRated: 'सर्वोत्तम रेटिंग',
      lowestRate: 'सर्वात कमी दर',
      highestRate: 'सर्वात जास्त दर',
      all: 'सर्व',
      noWorkers: 'तुमच्या निकषांशी जुळणारे कामगार सापडले नाहीत.',
      clearFilters: 'फिल्टर काढा',
      workerFallback: 'कामगार',
      kmAway: '{{distance}} किमी दूर',
      minsReach: '~{{minutes}} मिनिटांत पोहोच',
    },
    profile: {
      cannotBookWorkers: 'कामगार इतर कामगारांना बुक करू शकत नाहीत. कृपया ग्राहक म्हणून साइन इन करा.',
      workerNotFound: 'कामगार सापडला नाही.',
      browseWorkers: 'कामगार पाहा',
      backToWorkers: 'कामगारांकडे परत जा',
      unknownWorker: 'अज्ञात कामगार',
      verified: 'सत्यापित',
      reviews: '{{count}} परीक्षणे',
      perHour: '/तास',
      bookNow: 'आता बुक करा',
      about: 'परिचय',
      noBio: 'परिचय उपलब्ध नाही.',
      skills: 'कौशल्ये आणि विशेषता',
      highlights: 'ठळक वैशिष्ट्ये',
      backgroundVerified: '100% पार्श्वभूमी सत्यापित',
      directUpi: 'थेट UPI पेमेंट',
      promptResponse: 'जलद प्रतिसाद दर',
      customWork: 'विशेष काम हवे आहे?',
      customWorkDescription: 'बुकिंगच्या टप्प्यात तुम्ही नेमक्या गरजा आणि विशेष सूचना देऊ शकता.',
      requestService: 'सेवेची विनंती करा',
      customerReviews: 'ग्राहक परीक्षणे ({{count}})',
      reviewOne: 'अत्यंत कुशल, वेळेवर आले आणि समस्या पटकन सोडवली. नक्की शिफारस!',
      reviewTwo: 'अतिशय नम्र आणि व्यावसायिक. स्वच्छ काम आणि योग्य तासाचा दर.',
    },
    booking: {
      currentGpsLocation: 'सध्याचे GPS ठिकाण (अक्षांश: {{lat}}, रेखांश: {{lng}})',
      locationError: 'तुमचे ठिकाण मिळू शकले नाही. कृपया पत्ता स्वतः टाका.',
      geoUnsupported: 'या डिव्हाइसवर जिओलोकेशन उपलब्ध नाही.',
      requiredFields: 'कृपया सर्व आवश्यक माहिती भरा',
      futureTime: 'नियोजित वेळ भविष्यातील असावी',
      createFailed: 'बुकिंग तयार करणे अयशस्वी झाले',
      workerNotFound: 'कामगार सापडला नाही.',
      browseWorkers: 'कामगार पाहा',
      professionalWorker: 'व्यावसायिक कामगार',
      backToProfile: 'प्रोफाइलवर परत जा',
      title: 'अपॉइंटमेंट बुक करा',
      subtitle: '{{name}} सोबत सेवा नियोजित करा',
      verifiedProfessional: 'सत्यापित व्यावसायिक',
      kmAway: '{{distance}} किमी दूर',
      minsReach: '~{{minutes}} मिनिटांत पोहोच',
      dateTime: 'दिनांक आणि वेळ',
      date: 'दिनांक',
      time: 'वेळ',
      duration: 'कालावधी (तास)',
      hours: 'तास',
      serviceLocation: 'सेवेचे ठिकाण आणि लाइव्ह GPS',
      liveRadarReady: 'लाइव्ह रडार तयार',
      address: 'पत्ता / फ्लॅट / लँडमार्क',
      addressPlaceholder: 'तुमचा संपूर्ण पत्ता टाका...',
      useGps: 'माझे सध्याचे GPS ठिकाण वापरा',
      liveProximity: 'लाइव्ह अंतर: {{distance}} किमी',
      workerStationed: 'कामगार {{location}} जवळ उपलब्ध आहे',
      defaultLocation: 'बेंगळुरू',
      problemNotes: 'समस्येचे वर्णन आणि सूचना',
      notesPlaceholder: 'समस्या सांगा (उदा. इन्व्हर्टर ट्रिपिंग, बाथरूम पाईप गळती, पंख्याचा कॅपॅसिटर बदलणे)...',
      summary: 'बुकिंग सारांश',
      worker: 'कामगार',
      category: 'श्रेणी',
      durationValue: '{{hours}} तास',
      rate: 'दर',
      rateValue: '₹{{rate}}/तास',
      distance: 'अंतर',
      distanceValue: '{{distance}} किमी (~{{minutes}} मिनिटे)',
      totalAmount: 'एकूण रक्कम (0% शुल्क)',
      dispatching: 'पाठवले जात आहे...',
      launchRadar: 'GPS रडार आणि जुळणी सुरू करा',
    },
    payment: {
      validUtr: 'कृपया वैध 12 अंकी UTR / संदर्भ क्रमांक टाका',
      notFound: 'बुकिंग किंवा पेमेंट रेकॉर्ड सापडले नाही.',
      goDashboard: 'डॅशबोर्डवर जा',
      backDashboard: 'डॅशबोर्डवर परत जा',
      closeSlip: 'स्लिप दृश्य बंद करा',
      settlementCompleted: 'पेमेंट पूर्ण झाले',
      professionalWorker: 'व्यावसायिक कामगार',
      verifiedCustomer: 'सत्यापित ग्राहक',
      successUtr: 'UPI-REF-SUCCESS',
      quickTest: 'त्वरित टेस्ट स्लिप / Toing',
      title: 'पेमेंट गेटवे',
      subtitle: 'UPI द्वारे थेट कामगाराला पेमेंट',
      totalPayable: 'देय एकूण रक्कम',
      workerVerifying: 'कामगार UTR तपासत आहे',
      workerAccepted: 'कामगाराने स्वीकारले आणि तयार आहे',
      awaitingAcceptance: 'कामगाराच्या स्वीकृतीची प्रतीक्षा',
      qrLocked: 'QR कोड लॉक आहे',
      waitingFor: '{{name}} ने हे काम स्वीकारण्याची प्रतीक्षा आहे.',
      qrDescription: 'कामगाराच्या डॅशबोर्डवर Accept दाबताच UPI QR कोड आणि पेमेंट तपशील आपोआप अनलॉक होतील.',
      livePolling: 'कामगाराची स्थिती लाइव्ह तपासली जात आहे...',
      jobConfirmed: '{{name}} ने कामाची पुष्टी केली',
      liveUpi: 'लाइव्ह UPI चॅनेल',
      scanPay: 'UPI द्वारे पेमेंट करण्यासाठी स्कॅन करा',
      scanWith: 'GPay, PhonePe, Paytm किंवा BHIM ने स्कॅन करा',
      workerUpi: 'कामगार UPI:',
      copied: 'कॉपी झाले!',
      copy: 'कॉपी',
      launchApp: 'किंवा इंस्टॉल केलेल्या अॅपमधून थेट उघडा:',
      submitTitle: 'UPI संदर्भ (UTR) पाठवा',
      submitDescription: 'UPI अॅपमध्ये पेमेंट केल्यानंतर कामगाराच्या पुष्टीसाठी 12 अंकी UTR क्रमांक टाका.',
      paymentSubmitted: 'पेमेंट पाठवले - कामगाराच्या पुष्टीची प्रतीक्षा',
      submittedUtr: 'पाठवलेला UTR: {{utr}}',
      alertDispatched: '{{name}} ला त्वरित सूचना पाठवली आहे. सत्यापनानंतर स्लिप आपोआप प्रिंट होईल.',
      polling: 'कामगाराच्या पुष्टीची स्थिती तपासली जात आहे...',
      utrLabel: '12 अंकी बँक UTR / व्यवहार संदर्भ',
      utrPlaceholder: 'उदा. 483920194821',
      confirmFailed: 'पेमेंटची पुष्टी अयशस्वी झाली',
      workerFallback: 'कामगार',
      submitting: 'कामगाराला पाठवले जात आहे...',
      submitButton: 'कामगाराच्या पुष्टीसाठी पाठवा',
      protocol: 'CoLabour Direct-to-Worker UPI प्रोटोकॉल 0% कमिशनची हमी देतो.',
    },
    customer: {
      dashboardTitle: 'माझे ग्राहक डॅशबोर्ड',
      welcome: 'पुन्हा स्वागत आहे, {{name}}',
      bookWorker: 'कामगार बुक करा',
      activeBookings: 'सक्रिय बुकिंग',
      completedPaid: 'पूर्ण आणि पेमेंट झालेली',
      totalSpent: 'एकूण खर्च',
      pendingPayments: 'प्रलंबित पेमेंट',
      pendingAlert: 'तुमची {{count}} पेमेंट कृती प्रलंबित आहे',
      pendingDescription: 'बुकिंग पूर्ण करण्यासाठी UPI पेमेंट पूर्ण करा किंवा त्याचा मागोवा घ्या',
      openGateway: 'पेमेंट गेटवे उघडा',
      noActive: 'सक्रिय बुकिंग नाहीत',
      browseWorkers: 'कामगार पाहा',
      history: 'इतिहास आणि अधिकृत POS स्लिप',
      noCompleted: 'अजून पूर्ण बुकिंग नाही',
      workerFallback: 'कामगार',
      statusAccepted: 'स्वीकारले',
      statusPending: 'प्रलंबित',
      statusInProgress: 'प्रगतीपथावर',
      statusPaymentSubmitted: 'पेमेंट पाठवले',
      statusCompleted: 'पूर्ण',
      statusPaid: 'पैसे दिले',
      statusCancelled: 'रद्द',
      waitingAcceptance: 'स्वीकृतीची प्रतीक्षा',
      payWorker: 'कामगाराला UPI द्वारे पेमेंट करा',
      trackVerification: 'सत्यापनाचा मागोवा घ्या',
      paymentSettled: 'पेमेंट निकाली काढले',
      viewSlip: 'CoLabour स्लिप पाहा',
      professionalWorker: 'व्यावसायिक कामगार',
      verifiedCustomer: 'सत्यापित ग्राहक',
      officialUtr: 'UPI-OFFICIAL-UTR',
    },
    workerDashboard: {
      paymentConfirmed: 'पेमेंट मिळाल्याची पुष्टी झाली!',
      confirmPaymentFailed: 'पेमेंटची पुष्टी अयशस्वी झाली',
      jobAccepted: '🎉 काम यशस्वीपणे स्वीकारले! ग्राहकाला UPI पेमेंटची सूचना दिली.',
      jobDeclined: 'काम नाकारले आणि सक्रिय यादीतून काढले.',
      jobCompleted: 'काम पूर्ण म्हणून चिन्हांकित केले.',
      updateFailed: 'बुकिंग स्थिती अपडेट करणे अयशस्वी झाले',
      settingsSaved: 'सेटिंग्स यशस्वीपणे सेव्ह केल्या',
      settingsFailed: 'सेटिंग्स सेव्ह करणे अयशस्वी झाले',
      profileNotFound: 'कामगार प्रोफाइल सापडले नाही. कृपया नोंदणी पूर्ण करा.',
      completeRegistration: 'नोंदणी पूर्ण करा',
      dashboard: '{{name}} चे डॅशबोर्ड',
      workerId: 'कामगार ID: {{id}}',
      upi: 'UPI: {{upi}}',
      verified: 'सत्यापित',
      pending: 'प्रलंबित',
      settings: 'सेटिंग्स',
      totalEarnings: 'एकूण कमाई',
      activeRequests: 'सक्रिय विनंत्या',
      jobsSettled: 'निकाली काढलेली कामे',
      rating: 'रेटिंग',
      jobDispatches: 'काम वितरण आणि विनंत्या',
      noActiveRequests: 'सध्या कोणत्याही सक्रिय कामाच्या विनंत्या नाहीत',
      paymentConfirmations: 'पेमेंट पुष्टीकरण',
      noPayments: 'तुमच्या सत्यापनासाठी ग्राहकाचे कोणतेही पेमेंट प्रतीक्षेत नाही',
      settledJobs: 'निकाली काढलेली कामे आणि CoLabour स्लिप',
      noCompletedJobs: 'अजून पूर्ण कामे नाहीत',
      customerBooking: 'ग्राहकाचे बुकिंग',
      utr: 'UTR: {{utr}}',
      viewSlip: 'CoLabour स्लिप पाहा',
      workerSettings: 'कामगार सेटिंग्स',
      upiId: 'UPI ID',
      hourlyRate: 'तासाचा दर (₹)',
      save: 'सेव्ह करा',
      cancel: 'रद्द करा',
      customer: 'ग्राहक',
      accepted: 'स्वीकारले',
      note: 'टीप: {{note}}',
      acceptJob: 'काम स्वीकारा',
      decline: 'नकार द्या',
      acceptedPaying: 'काम स्वीकारले • ग्राहक UPI द्वारे पेमेंट करत आहे',
      markComplete: 'पूर्ण म्हणून चिन्हांकित करा',
      paymentAlert: 'पेमेंट मिळाल्याची सूचना',
      awaitingReceipt: 'पावतीची प्रतीक्षा',
      yesReceived: 'होय, मिळाले (पुष्टी करा)',
      professional: 'व्यावसायिक',
      verifiedCustomer: 'सत्यापित ग्राहक',
      officialUtr: 'OFFICIAL-PAID-UTR',
    },
    admin: {
      verificationFailed: 'सत्यापन अपडेट करणे अयशस्वी झाले',
      disputeFailed: 'वाद सोडवणे अयशस्वी झाले',
      title: 'अॅडमिन कमांड सेंटर',
      subtitle: 'संपूर्ण प्लॅटफॉर्मचे निरीक्षण आणि व्यवस्थापन',
      totalRevenue: 'एकूण महसूल',
      totalWorkers: 'एकूण कामगार',
      activeBookings: 'सक्रिय बुकिंग',
      openDisputes: 'उघडे वाद',
      workerVerifications: 'कामगार सत्यापन',
      pending: '{{count}} प्रलंबित',
      noWorkers: 'कोणतेही कामगार नोंदणीकृत नाहीत',
      unknown: 'अज्ञात',
      verified: 'सत्यापित',
      disputeLogs: 'वाद नोंदी',
      noDisputes: 'वाद नाहीत - सर्व ठीक आहे',
      paymentDispute: 'पेमेंट वाद',
      statusPending: 'प्रलंबित',
      utr: 'UTR: {{utr}}',
      amount: 'रक्कम: ₹{{amount}}',
      unresolved: 'न सुटलेला',
      resolve: 'सोडवा आणि पेमेंट म्हणून चिन्हांकित करा',
      telemetry: 'प्लॅटफॉर्म टेलिमेट्री',
      totalBookings: 'एकूण बुकिंग',
      completed: 'पूर्ण',
      verifiedWorkers: 'सत्यापित कामगार',
      totalPayments: 'एकूण पेमेंट',
    },
    alerts: {
      acceptFailed: 'बुकिंग स्वीकारणे अयशस्वी झाले',
      declineFailed: 'बुकिंग नाकारणे अयशस्वी झाले',
      confirmFailed: 'पेमेंटची पुष्टी अयशस्वी झाली',
      rejectFailed: 'पेमेंट नाकारणे अयशस्वी झाले',
      highPriority: 'उच्च-प्राधान्य काम वितरण',
      newRequest: 'नवीन सेवेची विनंती!',
      requestDescription: 'एका ग्राहकाने CoLabour वर तुमच्या कौशल्याची विनंती केली आहे.',
      customer: 'ग्राहक:',
      category: 'श्रेणी / कौशल्य:',
      totalValue: 'एकूण मूल्य:',
      scheduledAt: 'नियोजित वेळ:',
      location: 'ठिकाण:',
      verifiedCustomer: 'सत्यापित ग्राहक',
      customerNote: 'ग्राहकाची टीप:',
      decline: 'नकार द्या',
      acceptJob: 'काम स्वीकारा',
      verificationRequired: 'पेमेंट सत्यापन आवश्यक',
      paymentAlert: 'पेमेंट मिळाल्याची सूचना',
      paymentDescription: 'ग्राहकाने या कामासाठी UPI पेमेंटची पुष्टी पाठवली आहे.',
      totalClaimed: 'दावा केलेली एकूण रक्कम',
      bankUtr: '12 अंकी बँक UTR:',
      notAvailable: 'उपलब्ध नाही',
      timestamp: 'वेळ:',
      checkPayment: 'या व्यवहारासाठी तुमचे UPI अॅप / SMS अलर्ट तपासा. हे पेमेंट मिळाले का?',
      notReceived: 'नाही, मिळाले नाही',
      yesReceived: 'होय, मिळाले',
    },
    radar: {
      detecting: 'तुमचे लाइव्ह GPS ठिकाण शोधत आहे...',
      scanning: '5 किमीच्या आत सत्यापित कामगार शोधत आहे...',
      matching: 'सर्वात जवळच्या व्यावसायिकाशी जुळणी करत आहे...',
      found: 'कामगार सापडला! लाइव्ह सिग्नल लॉक झाला आणि स्वीकृतीची प्रतीक्षा आहे',
      title: 'लाइव्ह GPS रडार जुळणी',
      subtitle: 'CoLabour जवळीक वितरण',
      you: 'तुम्ही',
      kmAway: '{{distance}} किमी',
      minsReach: '~{{minutes}} मिनिटांत पोहोच',
      statusSequence: 'स्थिती क्रम',
      nearby: 'जवळपास',
      platformFee: '0% प्लॅटफॉर्म शुल्क',
      lockProceed: 'लॉक करा आणि पेमेंट गेटवेवर जा',
      acquiring: 'सॅटेलाइट लॉक मिळवत आहे...',
    },
    ai: {
      quickWiring: '⚡ वायरिंगचा खर्च जाणून घ्या',
      quickPlumber: '📍 माझ्या जवळ प्लंबर शोधा',
      quickUpi: '💸 शून्य शुल्क UPI आणि UTR मार्गदर्शक',
      quickSlip: '🧾 POS स्लिप कशी काम करते',
      welcome: '👋 नमस्कार! मी CoLabour AI, तुमचा स्मार्ट गिग सहाय्यक आहे. मी दुरुस्तीचा खर्च सांगू शकतो, जवळचा सत्यापित व्यावसायिक शोधू शकतो किंवा थेट 0% कमिशन UPI पेमेंट समजावू शकतो.',
      launcher: 'CoLabour AI ला विचारा',
      smart: 'स्मार्ट',
      title: 'CoLabour AI सहाय्यक',
      subtitle: '0% कमिशन • लाइव्ह जिओलोकेशन आणि स्मार्ट दर',
      mute: 'AI आवाज बंद करा',
      enable: 'AI आवाज सुरू करा',
      inputPlaceholder: 'दर, कामगार किंवा UPI पेमेंटबद्दल विचारा...',
      electricalEstimate: '⚡ **विद्युत कामाचा अंदाज:**\n• **सामान्य खर्च:** पॉइंटनुसार ₹350 - ₹650\n• **अंदाजे वेळ:** 45 - 90 मिनिटे\n• **शून्य प्लॅटफॉर्म शुल्क:** कामगाराकडून ₹0 कपात\n\nतुम्हाला राजेश कुमार (टॉप रेटेड इलेक्ट्रिशियन, ₹450/तास) बुक करायचे आहेत का?',
      bookRajesh: 'राजेश कुमार बुक करा (इलेक्ट्रिशियन)',
      plumbingMatch: '📍 **प्लंबिंग सेवा जुळणी:**\n• **अंदाजे खर्च:** ₹300 - ₹500\n• **सामान्य उपाय वेळ:** 30 - 60 मिनिटे\n\nसर्वोत्तम जुळणी: **{{name}}** (⭐ {{rating}}, ₹{{rate}}/तास). उच्च-दाब गळती दुरुस्तीसाठी सत्यापित.',
      bookWorker: '{{name}} बुक करा',
      plumbingFallback: '📍 **प्लंबिंग सेवा जुळणी:**\nसर्वोत्तम सत्यापित जुळणी **अमित पटेल** (⭐ 4.9, ₹400/तास) आहे. लपलेल्या पाईपची दुरुस्ती, नळ आणि गिझरमध्ये तज्ज्ञ.',
      bookAmit: 'अमित पटेल बुक करा (प्लंबर)',
      cleaning: '🧹 **डीप क्लीनिंग आणि निर्जंतुकीकरण:**\n• **1 BHK / सामान्य:** ₹700 - ₹1,200\n• **किचन आणि बाथ डीप क्लीन:** ₹400 - ₹800\n• **पर्यावरणपूरक उत्पादने:** पाळीव प्राण्यांसाठी 100% सुरक्षित\n\nसर्वोत्तम जुळणी: **प्रिया शर्मा** (⭐ 4.8, ₹350/तास).',
      bookPriya: 'प्रिया शर्मा बुक करा (क्लीनर)',
      upiGuide: '💸 **CoLabour Direct UPI कसे काम करते:**\n1. **थेट व्यक्ती-ते-व्यक्ती:** तुमचे 100% पैसे UPI द्वारे थेट कामगाराच्या बँक खात्यात जातात. CoLabour **0% कमिशन** घेते.\n2. **लॉक स्थिती:** कामगाराने बुकिंग स्वीकारताच QR कोड उघडतो.\n3. **UTR सत्यापन:** कामगाराला त्वरित सूचना देण्यासाठी तुमच्या बँकेचा 12 अंकी व्यवहार ID (UTR) टाका.\n4. **अधिकृत POS स्लिप:** डिजिटल स्वाक्षरी केलेली POS थर्मल स्लिप पावती मिळवा.',
      browseWorkers: 'सत्यापित कामगार पाहा',
      slipEngine: '🧾 **CoLabour 3D थर्मल स्लिप इंजिन:**\nप्रत्येक पूर्ण आणि सत्यापित बुकिंगसाठी अधिकृत POS हार्डवेअर पावती तयार होते, ज्यात असते:\n• शून्य शुल्क तपशील\n• 12 अंकी बँक UTR नोंद\n• प्रमाणित QR स्टॅम्प\n• PDF डाउनलोड आणि थेट थर्मल प्रिंटर आउटपुट.',
      openDashboard: 'ग्राहक डॅशबोर्ड उघडा',
      defaultResponse: '✨ मी त्वरित GPS जवळीक जुळणीसह प्रमाणित इलेक्ट्रिशियन, प्लंबर, सुतार आणि क्लीनर शोधण्यात मदत करू शकतो.\n\nकाय दुरुस्त करायचे ते सांगा (उदा. "सीलिंग फॅन दुरुस्त करा", "किचन पाईप गळत आहे") किंवा सत्यापित व्यावसायिकांची डायरेक्टरी पाहा.',
      exploreDirectory: 'सर्व कामगारांची डायरेक्टरी पाहा',
    },
    printer: {
      terminal: 'COLABOUR-POS // 4.2K',
      online: 'ऑनलाइन',
      ready: 'CoLabour थर्मल POS तयार',
      readyDescription: 'कामगाराने पेमेंटची पुष्टी केली आहे. छेडछाड-प्रतिबंधक डिजिटल कामाची स्लिप काढण्यासाठी बटण दाबा.',
      dispense: '⚡ स्लिप काढण्यासाठी टॅप करा',
      printing: 'थर्मल स्लिप प्रिंट होत आहे...',
      ejecting: 'एन्क्रिप्टेड थर्मल पावती बाहेर काढत आहे...',
      platform: 'ऑन-डिमांड कुशल सेवा प्लॅटफॉर्म',
      taxInvoice: 'टॅक्स इनव्हॉइस / सेवा पावती',
      bookingId: 'बुकिंग ID:',
      dateTime: 'दिनांक आणि वेळ:',
      customer: 'ग्राहक:',
      worker: 'कामगार:',
      category: 'श्रेणी:',
      workerUpi: 'कामगार UPI:',
      bankUtr: 'बँक UTR:',
      paymentStatus: 'पेमेंट स्थिती:',
      confirmedPaid: 'पुष्टी झाली (पेमेंट केले)',
      laborCharge: 'सेवा शुल्क:',
      commission: 'प्लॅटफॉर्म कमिशन:',
      zeroFee: '₹0.00 (शून्य शुल्क)',
      totalPaid: 'एकूण पेमेंट:',
      verifiedSlip: 'सत्यापित स्लिप',
      verifyAuthenticity: 'प्रामाणिकता तपासण्यासाठी स्कॅन करा',
      secured: 'सुरक्षित',
      thankYou: '*** CoLabour निवडल्याबद्दल धन्यवाद ***',
      printPdf: 'प्रिंट / PDF सेव्ह करा',
      backDashboard: 'डॅशबोर्डवर परत जा',
    },
  },
};

interface LanguageContextValue {
  language: Language;
  locale: string;
  setLanguage: (language: Language) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
  categoryName: (category: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const locales: Record<Language, string> = {
  en: 'en-IN',
  hi: 'hi-IN',
  mr: 'mr-IN',
};

function isLanguage(value: string | null): value is Language {
  return value !== null && supportedLanguages.includes(value as Language);
}

function getInitialLanguage(): Language {
  if (typeof window === 'undefined') return 'en';

  const savedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return isLanguage(savedLanguage) ? savedLanguage : 'en';
}

function getTranslation(language: Language, key: string): string {
  const read = (source: unknown): unknown => {
    return key.split('.').reduce<unknown>((value, part) => {
      if (typeof value !== 'object' || value === null) return undefined;
      return (value as Record<string, unknown>)[part];
    }, source);
  };

  const translated = read(translations[language]);
  const fallback = read(translations.en);
  return typeof translated === 'string' ? translated : typeof fallback === 'string' ? fallback : key;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.title = language === 'en'
      ? 'CoLabour — Futuristic Gig Worker Marketplace'
      : language === 'hi'
      ? 'CoLabour — आधुनिक गिग कामगार मार्केटप्लेस'
      : 'CoLabour — आधुनिक गिग कामगार मार्केटप्लेस';
  }, [language]);

  const t = (key: string, values?: Record<string, string | number>) => {
    const text = getTranslation(language, key);
    return Object.entries(values ?? {}).reduce(
      (result, [name, value]) => result.split(`{{${name}}}`).join(String(value)),
      text,
    );
  };

  const categoryName = (category: string) => translations[language].categories[category] ?? category;

  return (
    <LanguageContext.Provider value={{ language, locale: locales[language], setLanguage, t, categoryName }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
